<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<definitions
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://webservice.server.gpstracker.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://webservice.server.gpstracker.com/"
	name="GpsLocationServiceService">
	<types>
		<xsd:schema>
			<xsd:import namespace="http://webservice.server.gpstracker.com/"
				schemaLocation="GpsLocationServiceService_schema1.xsd" />
		</xsd:schema>
	</types>
	<message name="gpsLocationRQ">
		<part name="parameters" element="tns:gpsLocationRQ" />
	</message>
	<message name="gpsLocationRQResponse">
		<part name="parameters" element="tns:gpsLocationRQResponse" />
	</message>
	<portType name="GpsLocationService">
		<operation name="gpsLocationRQ">
			<input
				wsam:Action="http://webservice.server.gpstracker.com/GpsLocationService/gpsLocationRQRequest"
				message="tns:gpsLocationRQ" />
			<output
				wsam:Action="http://webservice.server.gpstracker.com/GpsLocationService/gpsLocationRQResponse"
				message="tns:gpsLocationRQResponse" />
		</operation>
	</portType>
	<binding name="GpsLocationServicePortBinding" type="tns:GpsLocationService">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="document" />
		<operation name="gpsLocationRQ">
			<soap:operation soapAction="" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>
	<service name="GpsLocationServiceService">
		<port name="GpsLocationServicePort" binding="tns:GpsLocationServicePortBinding">
			<soap:address location="http://localhost:8080/gpsTracker/gpsTracker" />
		</port>
	</service>
</definitions>

